### ISSUE TITLE
Add -manual to manual tests?

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-tests#9]
In WPT, `-manual` is [appended](https://web-platform-tests.org/writing-tests/file-names.html) in the filename before the extension to indicate a manual test. Should we add that to the files in the i18n test suite too?

/cc @r12a

**Comment by r12a** [comment]
@xfq yes, i have been asking myself the same question.

I think my conclusion is no.  Mainly because we sometimes link directly to tests from our other resources (eg. gap-analysis docs) and those links would then break. This applies to existing tests, but could also apply to future tests if we start out as manual but then figure out how to make them into ref or scripted tests (which has happened to a significant number of tests in the past).

The addition of the -manual would then be one of the things we would put on the list of steps involved in migrating tests to WPT.  When tracking tests between WPT repo and i18n repo  the difference in name shouldn't be to problematic if that's the only change to the filename.

Make sense?

**Comment by xfq** [comment]
Although I would like more consistency between the WPT repo and i18n repo, the cost of updating the links is not trivial, so I agree with you.

Should I close this issue?

**Comment by r12a** [comment]
Yes, let's close. I think we should try to ensure that the filename is the same except for any addition of -manual, so that there's as much consistency as possible in the names.
